sex 08 abr 2022 03:18:39 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/chili-clonedisk b/chili-clonedisk
--- a/chili-clonedisk
+++ b/chili-clonedisk
@@ -31,6 +31,7 @@
 #  contains portion of software https://bananapkg.github.io/
 #########################################################################
 #set -e
+declare -r APP="${0##*/}"
 declare -r _APP_="chili-clonedisk"
 declare -r _VERSION_="v2.0.3-20220407"
 readonly DEPENDENCIES=(which lsblk cut dialog whiptail pv grep sed cat awk tput dd)
@@ -982,8 +983,10 @@ sh_display
 ##############################################################################################################
 #TEMP=$(getopt -o vnh: --long version,nocolor,help:,debugfile:,minheap:,maxheap: -n 'clonedisk' -- "$@")
 #if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
-TEMP=$(getopt -o vnh --long version,nocolor,help,debugfile:,minheap:,maxheap: -n 'clonedisk' -- "$@")
-if [ $? != 0 ] ; then usage; exit 1 ; fi
+if ! TEMP=$(getopt -o vnh --long version,nocolor,help -n ${0##*/} -- "$@")
+then
+	usage; exit 1
+fi
 eval set -- "$TEMP"
 while true; do
 	case "$1" in
@@ -994,6 +997,32 @@ while true; do
 		*) break;;
 	esac
 done
+
+aflag=no
+bflag=no
+cargument=none
+
+# options may be followed by one colon to indicate they have a required argument
+if ! options=$(getopt -o abc: -l along,blong,clong: -n 'clonedisk' -- "$@")
+then
+    # something went wrong, getopt will put out an error message for us
+    exit 1
+fi
+set -- $options
+while [ $# -gt 0 ]
+do
+	case $1 in
+   -a|--along) aflag="yes" ;;
+   -b|--blong) bflag="yes" ;;
+   # for options with required arguments, an additional shift is required
+   -c|--clong) cargument="$2" ; shift;;
+   (--) shift; break;;
+   (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
+   (*) break;;
+   esac
+   shift
+done
+
 init
 
 :<<'LIXO'
