qui 04 ago 2022 06:29:29 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/fetch b/fetch
--- a/fetch
+++ b/fetch
@@ -161,7 +161,7 @@ configure()
 }
 
 sh_touchconf(){
-	[[ -d "${SYSCONFDIR}" ]] || mkdir -p 2>&-
+	[[ -d "${SYSCONFDIR}" ]] || mkdir -p >/dev/null 2>&-
 	cat > "$SYSCONFDIR/fetch.conf" << '_EOF_'
 ######################################################################
 # fetch.conf
@@ -728,7 +728,7 @@ sh_selfupdate()
 		#Ok, Puxe o arquivo do repositorio agora!
 		[[ -d "${tmp_dir_full}" ]] && rm -r "${tmp_dir_full}"
 		[[ -d "${tmp_dir}" ]] || mkdir -p "${tmp_dir}"
-		pushd "${tmp_dir}" 2>&- || return 1
+		pushd "${tmp_dir}" >/dev/null 2>&- || return 1
 		log_info_msg "${cyan}Clonando $link"
 		curl --insecure --silent --remote-name "${link}"
 		evaluate_retval
@@ -807,7 +807,7 @@ sh_checkdir()
 		if [[ -d "$i" ]]; then
 			(( verbose >= 2 )) && evaluate_retval
 		else
-			mkdir -p "$i"  2>&-
+			mkdir -p "$i"  >/dev/null 2>&-
 			(( verbose >= 2 )) && evaluate_retval
 		fi
 	done
@@ -841,7 +841,7 @@ fn_updaterepo()
 		return 1
 	fi
 
-	pushd "$CACHEDIR_SEARCH/" 2>&- || return 1
+	pushd "$CACHEDIR_SEARCH/" >/dev/null 2>&- || return 1
 	sh_backup
 
 	log_msg "${pink}Cleaning up ${CACHEDIR_SEARCH}/${reset}"
@@ -861,7 +861,7 @@ fn_updaterepo()
 	log_msg "${green}($(strzero "$nfilesInstalled" 5)) installed packages${reset}"
 	echo
 	log_msg "${reset}Use: # ${0##*/} --help for helping${reset}"
-	popd 2>&- || return 1
+	popd >/dev/null 2>&- || return 1
 }
 
 # -Syy
@@ -896,7 +896,7 @@ fn_update()
 		exit 1
 	fi
 
-	pushd "$CACHEDIR_SEARCH/" 2>&- || return 1
+	pushd "$CACHEDIR_SEARCH/" >/dev/null 2>&- || return 1
 	sh_backup
 
 	log_msg "${pink}Cleaning up $CACHEDIR_SEARCH/"
@@ -961,7 +961,7 @@ fn_update()
 	log_msg "${red}$(strzero "$nfilesInCache" 5) ${bold}${green}packages in cache $CACHEDIR_ARCHIVES"
 	echo
 	log_msg "${reset}Use: # ${0##*/} --help for helping${reset}"
-	popd 2>&- || return 1
+	popd >/dev/null 2>&- || return 1
 }
 
 fn_updateOLD()
@@ -995,7 +995,7 @@ fn_updateOLD()
 		exit 1
 	fi
 
-	pushd "$CACHEDIR_SEARCH/" 2>&- || return 1
+	pushd "$CACHEDIR_SEARCH/" >/dev/null 2>&- || return 1
 	sh_backup
 
 	log_msg "${pink}Cleaning up ${CACHEDIR_SEARCH}/${reset}"
@@ -1090,7 +1090,7 @@ comment
 	log_msg "${green}($(strzero "$nfilesInCache" 5)) packages in cache $CACHEDIR_ARCHIVES${reset}"
 	echo
 	log_msg "${reset}Use: # ${0##*/} --help for helping${reset}"
-	popd 2>&- || return 1
+	popd >/dev/null 2>&- || return 1
 }
 
 fn_updateMazon()
@@ -1121,7 +1121,7 @@ fn_updateMazon()
 		exit 1
 	fi
 
-	pushd "$CACHEDIR_SEARCH/" 2>&- || return 1
+	pushd "$CACHEDIR_SEARCH/" >/dev/null 2>&- || return 1
 	sh_backup
 
 	log_msg "${pink}Cleaning up ${CACHEDIR_SEARCH}/${reset}"
@@ -1210,7 +1210,7 @@ fn_updateMazon()
 	log_msg "${green}($(strzero "$nfilesInCache" 5)) packages in cache $CACHEDIR_ARCHIVES${reset}"
 	echo
 	log_msg "${reset}Use: # ${0##*/} --help for helping${reset}"
-	popd 2>&- || return 1
+	popd >/dev/null 2>&- || return 1
 }
 
 sh_filesincache()
@@ -1535,31 +1535,31 @@ sh_remove_now()
 	local cPkgBaseVersion="${1/%.${PKG_EXT}/}"
 	local thefile
 
-	pushd "/" 2>&- || return 1
+	pushd "/" >/dev/null 2>&- || return 1
 
 	if [[ -e "${CACHEDIR_REMO}/${cPkgBaseVersion}.rm" ]]; then
-		sed -E "/rm[[:space:]]+\-(rf|fr)/d" "${CACHEDIR_REMO}/${cPkgBaseVersion}.rm" 2>&-
+		sed -E "/rm[[:space:]]+\-(rf|fr)/d" "${CACHEDIR_REMO}/${cPkgBaseVersion}.rm" >/dev/null 2>&-
 		bash "${CACHEDIR_REMO}/${cPkgBaseVersion}.rm"
-		rm "${CACHEDIR_REMO}/${cPkgBaseVersion}.rm" 2>&-
+		rm "${CACHEDIR_REMO}/${cPkgBaseVersion}.rm" >/dev/null 2>&-
 	fi
 
 	while IFS= read -r thefile; do
 		if [[ -f "$thefile" ]]; then
-			rm "$thefile" 2>&- && print "Delete\t${thefile}"
+			rm "$thefile" >/dev/null 2>&- && print "Delete\t${thefile}"
 		fi
 		if [[ -L "$thefile" ]]; then
-			unlink "$thefile" 2>&-
+			unlink "$thefile" >/dev/null 2>&-
 		fi
 		if [[ -d "$thefile" ]] && [[ -z "$(ls -A "$thefile")" ]]; then
-			rmdir -p "${thefile}" 2>&-
+			rmdir -p "${thefile}" >/dev/null 2>&-
 		fi
 	done < "${CACHEDIR_LIST}/${cPkgBaseVersion}.list"
 
-	popd 2>&- || return 1
+	popd >/dev/null 2>&- || return 1
 	IFS=$SAVEIFS
 
-	if ! rm "$CACHEDIR_DESC/$cPkgBaseVersion.desc" 2>&-; then { log_failure_msg2 "Error, It was not possible remove $CACHEDIR_DESC/$cPkgBaseVersion.desc" ; return 1; } fi
-	if ! rm "$CACHEDIR_LIST/$cPkgBaseVersion.list" 2>&-; then { log_failure_msg2 "Error, It was not possible remove $CACHEDIR_LIST/$cPkgBaseVersion.list" ; return 1; } fi
+	if ! rm "$CACHEDIR_DESC/$cPkgBaseVersion.desc" >/dev/null 2>&-; then { log_failure_msg2 "Error, It was not possible remove $CACHEDIR_DESC/$cPkgBaseVersion.desc" ; return 1; } fi
+	if ! rm "$CACHEDIR_LIST/$cPkgBaseVersion.list" >/dev/null 2>&-; then { log_failure_msg2 "Error, It was not possible remove $CACHEDIR_LIST/$cPkgBaseVersion.list" ; return 1; } fi
 	return $ERR_OK
 }
 
@@ -1592,7 +1592,7 @@ sh_pre_removeOLD()
 	local q
 	local alldesc=$cPkgBaseVersion.desc
 
-	pushd "$CACHEDIR_DESC" 2>&- || return 1
+	pushd "$CACHEDIR_DESC" >/dev/null 2>&- || return 1
 	for search_pack in $alldesc; do
 		if [[ "$search_pack" =~ ^${re}.* ]]; then
 			for q in *; do
@@ -1603,7 +1603,7 @@ sh_pre_removeOLD()
 
 			[[ -e "$CACHEDIR_DESC/$search_pack" ]] && source "$CACHEDIR_DESC/$search_pack"
 			name_version_build="$cPkgBaseVersion"
-			pushd "${CACHEDIR_LIST}" 2>&- || return 1
+			pushd "${CACHEDIR_LIST}" >/dev/null 2>&- || return 1
 			search_pack="${search_pack/%.desc/.list}" # se terminar com .desc substitua por .list
 #			[[ -e "${search_pack}" ]] && { sh_remove_now "$name_version_build"; return 0 ;} || { log_failure_msg2 "ERROR: FILE NOT FOUND ${CACHEDIR_LIST}/${search_pack}"; return 1;}
 			if [[ -e "${search_pack}" ]]; then
@@ -1636,7 +1636,7 @@ sh_download()
 	local ntotal_pkg_listed="${public_ntotal_pkg_listed}"
 
 	if [[ $public_pkg != "" ]]; then
-		pushd "$CACHEDIR_ARCHIVES/" 2>&- || return 1
+		pushd "$CACHEDIR_ARCHIVES/" >/dev/null 2>&- || return 1
 		#internet?
 		sh_checknet || return 1
 
@@ -1665,7 +1665,7 @@ sh_download()
 			fi
 		done
 		log_msg "${cyan}($nFilesDownloaded) packages(s) downloaded."
-		popd 2>&- || return 1
+		popd >/dev/null 2>&- || return 1
 	fi
 }
 
@@ -1986,7 +1986,7 @@ sh_wgetresponse()
 	(( verbose >= 2 )) && evaluate_retval $lresult
 
 	if ! [[ $response -eq 200 ]]; then
-		rm -f "$cfullfilename" 2>&-
+		rm -f "$cfullfilename" >/dev/null 2>&-
 		if ! (( LSKIPERROR )); then
 			log_failure_msg "${red}error${reset}: $response NOT FOUND file ${orange}${cfile} ${reset}at $SITE/packages/ - Use the ${yellow}--skiperror ${reset}option to skip install."
 		else
@@ -2008,10 +2008,10 @@ sh_wgetdesc()
 	else
 		cRaw=$RAW	#github
 	fi
-	pushd "$CACHEDIR_ARCHIVES/" 2>&-
+	pushd "$CACHEDIR_ARCHIVES/" >/dev/null 2>&-
 	sh_wgetresponse "$i.desc"
 	nretval=$?
-	popd 2>&-
+	popd >/dev/null 2>&-
 	return $nretval
 }
 
@@ -2141,7 +2141,7 @@ sh_installmeta()
 			LAUTO=$true
 		fi
 
-		pushd "$CACHEDIR_ARCHIVES/" 2>&- || return 1
+		pushd "$CACHEDIR_ARCHIVES/" >/dev/null 2>&- || return 1
 		for cmetafile in $metapkg; do
 			cmetapackage=$(echo "$cmetafile" | cut -d/ -f2)
 
@@ -2153,7 +2153,7 @@ sh_installmeta()
 			pkgInMeta+=("$(cat "$CACHEDIR_ARCHIVES/$cmetapackage")")
 		done
 
-		popd 2>&- || return 1
+		popd >/dev/null 2>&- || return 1
 		param="$pkgInMeta"
 
 #		[[ $verbose -eq 0 ]] && (( verbose=1 ))
@@ -2186,10 +2186,10 @@ sh_recreateFilesFromArch()
 	local aCache
 
 	(( verbose >= 2 )) && log_msg "Fixing packages installed by pacman"
-	pushd "/var/lib/pacman/local/" 2>&- || return 1
+	pushd "/var/lib/pacman/local/" >/dev/null 2>&- || return 1
 	mapfile -t aCache < <(printf '%s\n' *)
 	nfiles=$(lenarray "${aCache[*]}")
-	popd 2>&- || return 1
+	popd >/dev/null 2>&- || return 1
 
    if (( nfiles )); then
    	for item in $aCache; do
@@ -2419,7 +2419,7 @@ sh_manage_scripts_and_archives()
 		return 1
 	fi
 
-	pushd "/tmp/info/" 2>&- || return 1
+	pushd "/tmp/info/" >/dev/null 2>&- || return 1
 	if ! mv '/tmp/info/desc' "$CACHEDIR_DESC/${packname}.desc" ; then
 		log_failure_msg2 "ERROR! could not move desc to /${dir_desc}/${packname}.desc"
 		return 1
@@ -2431,11 +2431,11 @@ sh_manage_scripts_and_archives()
 	fi
 
 	if [[ -e "/tmp/info/.INSTALL" ]]; then
-		source /tmp/info/.INSTALL 2>&-
+		source /tmp/info/.INSTALL >/dev/null 2>&-
 		log_msg "running post_install hook"
-		post_install 2>&-
+		post_install >/dev/null 2>&-
 		log_msg "running post_upgrade hook"
-		post_upgrade 2>&-
+		post_upgrade >/dev/null 2>&-
 	fi
 
 	if [[ -e "/tmp/info/rm.sh" ]]; then
@@ -2445,7 +2445,7 @@ sh_manage_scripts_and_archives()
 		fi
     fi
 
-	popd 2>&- || return 1
+	popd >/dev/null 2>&- || return 1
 	[[ -d "/info/"      ]] && rm -r "/info/"
    [[ -d '/tmp/info/'  ]] && rm -r "/tmp/info/"
    [[ -e '/.BUILDINFO' ]] && rm "/.BUILDINFO"
@@ -2504,7 +2504,7 @@ fn_generate_desc()
 	#DESC=$(echo "${DESC//\'}") 		# remove apostrofe. ex: let´s => lets
 	DESC=${DESC//\'} 						# remove apostrofe. ex: let´s => lets
 
-	[[ ! -d "info" ]] && mkdir info 2>&-
+	[[ ! -d "info" ]] && mkdir info >/dev/null 2>&-
 
 	if [ -e info/desc ]; then
 		(( ncount++ ))
@@ -2564,7 +2564,7 @@ sh_doinstallpkg()
 				--extract                     \
 				--preserve-permissions        \
 				--touch                       \
-				--file "${packname}" -C "/tmp/" "./${DESCME}" "./${PRE_SH}" "./${INSTALL_SH}" 2>&-
+				--file "${packname}" -C "/tmp/" "./${DESCME}" "./${PRE_SH}" "./${INSTALL_SH}" >/dev/null 2>&-
 
 	if [[ ! -e "/tmp/${DESCME}" ]]; then
 		log_failure_msg2 "${red}ERROR! ${reset}I could not untar the file: ${orange}${packname}.desc${reset}"
@@ -2693,9 +2693,9 @@ _GPG_SIGN()
 	[ "$REWRITE_SIGN" = "1" ] && rm -f "../$package.$PKG_EXT.$sig"
 	[ "$REWRITE_SIGN" = "1" ] && rm -f "$package.$PKG_EXT.$sig"
 
-	if which gpg 2>&-; then
+	if which gpg >/dev/null 2>&-; then
 		#Gerando Assinatura no pacote
-		gpg --detach-sign --pinentry-mode loopback "${package}.${PKG_EXT}" 2>&- || \
+		gpg --detach-sign --pinentry-mode loopback "${package}.${PKG_EXT}" >/dev/null 2>&- || \
 		gpg --detach-sign "${package}.${PKG_EXT}" || return 1
 		echo -e "${blue}[Create]${end} Your ${sig} on:   ../${package}.${PKG_EXT}.${sig}"
 	fi
@@ -2752,7 +2752,7 @@ fn_verify_on()
 
 	for check_script in 'pre.sh' 'pos.sh' 'rm.sh'; do
 		if [[ -e "${dir_info}/${check_script}" ]]; then
-	   	if _GREP 'rm[[:space:]]+\-(rf|fr)' "${dir_info}/${check_script}" 2>&-; then
+	   	if _GREP 'rm[[:space:]]+\-(rf|fr)' "${dir_info}/${check_script}" >/dev/null 2>&-; then
 		   	log_failure_msg2 "${red}ERROR ${reset}${PWD}/${dir_info}/$check_script contain command rm -rf. ABORTED NOW."
    			return 1
       	fi
@@ -2767,14 +2767,14 @@ fn_create_pkg()
 	local ext_desc='desc'
 
 	if tar --force-local --use-compress-program="zstd --ultra" --create --file ../"$package" .; then
-		cp "$DESCME" ../"$package.$ext_desc" 2>&-
-		pushd .. 2>&- || return 1
+		cp "$DESCME" ../"$package.$ext_desc" >/dev/null 2>&-
+		pushd .. >/dev/null 2>&- || return 1
 		if (( CREATE_SHA256 )); then
 			sha256sum "$package" > "$package".sha256
 		fi
 		if (( GPG_SIGN )); then
 			_GPG_SIGN "$package" || return 1
-			popd 2>&- || return 1
+			popd >/dev/null 2>&- || return 1
 		else
 			return 0
 		fi
@@ -2849,8 +2849,8 @@ fn_alienpkg_main()
 fn_alienpkg_initvars()
 {
 	BUILDDIR="${PKGCORE:=${CACHEDIR}/archives}"
-	[[ -n "${BUILDDIR}" ]] || BUILDDIR="${CACHEDIR}/archives" 2>&-
-	[[ -d "${BUILDDIR}" ]] || mkdir -p "${BUILDDIR}" 2>&-
+	[[ -n "${BUILDDIR}" ]] || BUILDDIR="${CACHEDIR}/archives" >/dev/null 2>&-
+	[[ -d "${BUILDDIR}" ]] || mkdir -p "${BUILDDIR}" >/dev/null 2>&-
 }
 
 fn_alienpkg_exec()
@@ -2929,18 +2929,18 @@ fn_alienpkg_exec()
 			destdir="$BUILDDIR/$pkgtar"
 			(( ++ncount ))
 			(( verbose >= 1 )) && log_msg "$(fmt) Creating directory $destdir"
-			mkdir -p "$destdir" 2>&-
+			mkdir -p "$destdir" >/dev/null 2>&-
 
 			(( ++ncount ))
 			(( verbose >= 1 )) && log_msg "$(fmt) Unpacking package $package at $destdir"
-			tar --use-compress-program=zstd --force-local --extract --file "$package" -C "$destdir" 2>&-
+			tar --use-compress-program=zstd --force-local --extract --file "$package" -C "$destdir" >/dev/null 2>&-
 
 			case $package in
 				luit-[0-9]* ) sed -i -e "/D_XOPEN/s/5/6/" configure;;
 			esac
 
-			sed -i 's/ = /="/g' "$destdir/.PKGINFO"  2>&-
-			sed -i 's/$/"/g'    "$destdir/.PKGINFO"  2>&-
+			sed -i 's/ = /="/g' "$destdir/.PKGINFO"  >/dev/null 2>&-
+			sed -i 's/$/"/g'    "$destdir/.PKGINFO"  >/dev/null 2>&-
 			source "$destdir/.PKGINFO"
 
 			export          DESC_BUILD="${pkgtar: -1}"
@@ -2955,8 +2955,8 @@ fn_alienpkg_exec()
 			export          DESC_BUILD="${pkgver: -1}"
 
 			deps=$(grep ^depend "$destdir"/.PKGINFO | awk -F'"' '{print $2}')
-			pushd "$destdir" 2>&- || return 1
-			rm -f "$destdir"/.BUILDINFO "$destdir"/.MTREE "$destdir"/.PKGINFO 2>&-
+			pushd "$destdir" >/dev/null 2>&- || return 1
+			rm -f "$destdir"/.BUILDINFO "$destdir"/.MTREE "$destdir"/.PKGINFO >/dev/null 2>&-
 
 			(( ++ncount ))
 			fn_createpkg "$pkgtar"
@@ -2978,7 +2978,7 @@ fn_alienpkg_exec()
 		log_failure_msg "${red}error: ${orange}$x ${reset}package target ${yellow}${param} ${reset}was ${red}NOT ${reset}found in ${yellow}${ALIEN_CACHE_DIR} ${reset}for import"
 	fi
 	unset size ncount ntotalpkg
-	popd 2>&- || return 1
+	popd >/dev/null 2>&- || return 1
 }
 
 fn_alienpkg_pkgsize()
@@ -3106,7 +3106,7 @@ checkDependencies()
 sh_cleaning()
 {
 	log_msg "${pink}Cleaning temporary files${reset}"
-	rm -rf "${TMP_DIR_ROOT:?}"/ 2>&-
+	rm -rf "${TMP_DIR_ROOT:?}"/ >/dev/null 2>&-
 }
 
 sh_backup()
@@ -3114,9 +3114,9 @@ sh_backup()
 	if (( verbose >= 2 )); then
 		log_msg "${pink}Making backup: $CACHEDIR_SEARCH/${reset}"
 	fi
-	mkdir -p "$TMP_DIR_BACKUP"/ 2>&-
-	mkdir -p "$TMP_DIR_FOLDERS"/ 2>&-
-	cp -f "$CACHEDIR_SEARCH"/* "$TMP_DIR_BACKUP"/ 2>&-
+	mkdir -p "$TMP_DIR_BACKUP"/ >/dev/null 2>&-
+	mkdir -p "$TMP_DIR_FOLDERS"/ >/dev/null 2>&-
+	cp -f "$CACHEDIR_SEARCH"/* "$TMP_DIR_BACKUP"/ >/dev/null 2>&-
 }
 
 sh_version()
@@ -3317,8 +3317,8 @@ cleanup()
 	echo
  	echo "Interrupt signal received"
 	log_msg "${pink}Cleaning...${reset}"
-	cp -f "$TMP_DIR_BACKUP"/* "$CACHEDIR_SEARCH"/ 2>&-
-	rm -rf "${TMP_ROOT_BACKUP}"/ 2>&-
+	cp -f "$TMP_DIR_BACKUP"/* "$CACHEDIR_SEARCH"/ >/dev/null 2>&-
+	rm -rf "${TMP_ROOT_BACKUP}"/ >/dev/null 2>&-
 	rm -f "/tmp/ARRAYPKGFULL"
 	kill -TERM -$$
 	exit
