sex 05 ago 2022 19:13:16 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/fetch b/fetch
--- a/fetch
+++ b/fetch
@@ -75,7 +75,7 @@ configure()
 {
 	export LC_ALL=C
 	export LANG=C
-	readonly DEPENDENCIES=(which find tar zstd curl sed grep cat awk tput stat tee lynx numfmt)
+	readonly DEPENDENCIES=(which find tar zstd curl sed sort grep cat awk tput stat tee lynx numfmt)
 	unset CDPATH
 	unset GREP_OPTIONS
 
@@ -2540,8 +2540,8 @@ fn_generate_desc()
 
 	cat > "info/desc" << EOF
 ######################################################################
-# Generated with fetch    - https://chilinux.com
-# Generated with alienpkg - https://chilinux.com
+# Generated with fetch    - https://chililinux.com
+# Generated with alienpkg - https://chililinux.com
 ######################################################################
 maintainer='$MAINTAINER'
 pkgname='$DESC_PACKNAME'
@@ -3159,6 +3159,242 @@ EOF
 	sh_version
 }
 
+fetchpack_configure()
+{
+	#  fetchpack - A flexible cache cleaning utility in ChiliOS
+	#########################################################################
+	declare -a cachedirs=() candidates=() cmdopts=() candesc=()
+	declare -i delete=0 dryrun=0 move=0 totalsaved=0 pkgcount=0
+	declare -i verbose=0 ctime=0 QUIET=0
+	declare delim=$'\n'
+	declare keep=3
+	declare movedir=
+	declare USE_COLOR='y'
+	# Expand to nothing if there are no matches
+	shopt -s nullglob
+	shopt -s extglob
+
+	# flag's para split package
+	: "${aPKGSPLIT=()}"
+	: "${aPKGLIST=}"
+	: "${PKG_FOLDER_DIR=0}"
+	: "${PKG_FULLNAME=1}"
+	: "${PKG_ARCH=2}"
+	: "${PKG_BASE=3}"
+	: "${PKG_BASE_VERSION=4}"
+	: "${PKG_VERSION=5}"
+	: "${PKG_BUILD=6}"
+}
+
+fetchpack_main()
+{
+	local nfiles=0
+	local pkg=
+	local pkgInAll=
+	local pkg_base=
+	local candidates=()
+	local cachedir
+	local re
+
+   #'[0-9]+([.][0-9]+)+'
+   #'-[0-9]+(.[0-9]+)+'
+   #'-[0-9]+([.][0-9]+)+'
+   #'[0-9]+([.][0-9]+)(.+)'
+   #'(([^-]+)-([0-9]+))-'
+   #'(.+)-(([^-]+)-([0-9]))-([^.]+)'
+   #'.*?(?=-[^-]+-[0-9]-.*)')
+   #'\-[^-]+-[0-9]-')
+ 	re='-[^-]+-[0-9]+-'
+
+	if (( QUIET )); then
+		verbose=0
+	else
+		if (( verbose )); then
+			if (( dryrun )); then
+		   	log_msg "${white}running mode => ${green}DRY-RUN"
+			elif (( delete )); then
+		   	log_msg "${white}running mode => ${red}DELETE"
+			elif (( move )); then
+		   	log_msg "${white}running mode => ${yellow}MOVE"
+			fi
+		fi
+	fi
+
+	for cachedir in "${cachedirs[@]}"
+	do
+		[[ -d $cachedir ]]            || die "Error: cachedir '$cachedir' does not exist or is not a directory"
+		pushd "$cachedir" &>/dev/null || die "Error: failed to chdir to $cachedir"
+
+		if [ $# -lt 1 ]; then
+ 			AllOldPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | sort -Vr | awk -F "$re" 'lista[$1]++')
+		else
+ 			AllOldPackages=$(find "$PWD" -type f -iname "*.$PKG_EXT" | grep "$1" | sort -Vr | awk -F "$re" 'lista[$1]++')
+		fi
+
+		while read -r pkgInAll; do
+			pkg_base="$pkgInAll"
+			[[ -z "$pkg_base" ]] &&	continue
+			(( pkgNumber++ ))
+
+			if (( verbose >= 3 )); then
+				printf "  $(DOT)${white}candidate package ${purple}(%04d) ${green}%s\n" "$pkgNumber" "$pkg_base"
+			fi
+
+			candidates+=("$pkgInAll")
+			candesc+=("$pkgInAll.desc")
+		done <<< "$AllOldPackages"  #done < <(printf '%s\n' "$AllOldPackages") #done <<< $(printf '%s\n' "$AllOldPackages")
+		popd >/dev/null 2>&1
+	done
+
+	if (( ! ${#candidates[*]} )); then
+		log_msg "${green}NO candidates packages found for pruning"
+		exit
+	fi
+
+	if (( verbose >= 2 )); then
+		pkgNumber=0
+		while read -r pkg; do
+			(( pkgNumber++ ))
+			printf "  $(DOT)${white}found package ${purple}(%04d) ${green}%42s\n" "$pkgNumber" "$pkg"
+		done <<< "$(printf '%s\n' "${candidates[@]}")"
+		#done < <(printf '%s\n' "${candidates[@]}") #done <<< "${candidates[@]}"
+	fi
+
+	pkgcount=$((${#candidates[*]} + ${#candesc[*]}))
+	totalsaved=$(printf '%s\0' "${candidates[@]}" | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
+	totalsaved+=$(printf '%s\0' "${candesc[@]}"   | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
+	set -o errexit # Exit immediately if a pipeline returns non-zero.
+
+	if (( delete )); then
+		(( verbose )) && cmdopts+=(-v); cmdopts+=(-f)
+		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
+		printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 rm "${cmdopts[@]}"
+	elif (( move )); then
+		(( verbose )) && cmdopts+=(-v); cmdopts+=(-f)
+		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
+		printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
+	elif (( verbose )); then
+		printf '%s\0' "${candidates[@]}" | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
+		printf '%s\0' "${candesc[@]}"    | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
+	fi
+
+	if (( !QUIET )); then
+		if (( dryrun )); then
+			msg "${yellow}$output finish dry-run (packages found: $pkgcount with .desc) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
+		else
+			msg "$output (packages found: $pkgcount with .desc) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
+		fi
+	fi
+	return 0
+}
+
+fetchpack_usage()
+{
+	cat <<EOF
+${cyan}Usage: ${yellow}fetch -Sc <operation> [options] [targets...]${reset}
+
+  Operations:
+${red}     -d, --dryrun          ${reset}perform a dry run, only finding candidate packages.
+${red}     -m, --move <dir>      ${reset}move candidate packages to "dir".
+${red}     -r, --remove          ${reset}remove candidate packages.
+
+  Options:
+${red}     -c, --cachedir <dir>  ${reset}scan "dir" for packages. can be used more than once.
+                           (default: read from /etc/fetch/fetch.conf).
+${red}     -k, --keep <num>      ${reset}keep "num" of each package in the cache (default: 3).
+${red}     -f, --force           ${reset}apply force to mv(1) and rm(1) operations.
+${red}     -h, --help            ${reset}display this help message and exit.
+${red}         --nocolor         ${reset}remove color from output.
+${red}     -q, --quiet           ${reset}quiet output.
+${red}     -v, --verbose         ${reset}increase verbosity. specify up to 3 times ([-v][-vv][-vvv]).
+
+${cyan}most common use: ${yellow}fetch -Sc -k1 -r -v${reset}
+EOF
+}
+
+fetchpack_init()
+{
+#	sh_checkroot
+#	checkDependencies
+	fetchpack_configure
+
+	OPT_SHORT=':a:c:dfhi:k:m:qrsuVvzt:'
+	OPT_LONG=('arch:' 'cachedir:' 'dryrun' 'force' 'help' 'ignore:' 'keep:' 'move:' 'nocolor' 'quiet' 'remove' 'uninstalled' 'version' 'verbose' 'null' 'ctime:')
+
+	if ! parseopts "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
+		exit 1
+	fi
+	set -- "${OPTRET[@]}"
+	unset OPT_SHORT OPT_LONG OPTRET
+
+	while :; do
+		case $1 in
+			-t|--ctime)
+				ctime="$2"
+				shift ;;
+			-c|--cachedir)
+				cachedirs+=("$2")
+				shift ;;
+			-d|--dryrun)
+				dryrun=1 ;;
+			-f|--force)
+				cmdopts=(-f) ;;
+			-h|--help)
+				fetchpack_usage
+				exit 0 ;;
+			-m|--move)
+				move=1 movedir=$2
+				shift ;;
+			--nocolor)
+				unsetvarcolors
+				USE_COLOR='n' ;;
+			-q|--quiet)
+				unsetvarcolors
+				QUIET=1 ;;
+			-r|--remove)
+				delete=1 ;;
+			-V|--version)
+				logo
+				exit 0 ;;
+			-v|--verbose)
+				(( ++verbose )) ;;
+			-z|--null)
+				delim='\0' ;;
+			--)
+				shift
+				break 2 ;;
+		esac
+		shift
+	done
+
+	# check if messages are to be printed using color
+	if [[ -t 2 && $USE_COLOR != "n" ]]; then
+		setvarcolors
+	fi
+
+	# setting default cachedirs
+	if [[ -z "${cachedirs[*]}" ]]; then
+		cachedirs=("${GITDIR:=/var/cache/fetch/archives}")
+		cachedirs+=("/var/cache/fetch/archives")
+	fi
+
+	# sanity checks
+	case $(( dryrun+delete+move )) in
+		0) 	die "no operation specified (use -Sc -h for help)" ;;
+		[^1]) die "only one operation may be used at a time" ;;
+	esac
+
+	[[ $movedir && ! -d $movedir ]] && die "destination directory '$movedir' does not exist or is not a directory!"
+
+	if (( move || delete )); then
+		# make it an absolute path since we're about to chdir
+		[[ $movedir && ${movedir:0:1} != '/' ]] && movedir=$PWD/$movedir
+		[[ $movedir && ! -w $movedir ]] && needsroot=1
+	fi
+
+	fetchpack_main "$@"
+}
+
 usage()
 {
 	tput sgr0; # reset colors
@@ -3279,7 +3515,8 @@ init()
 			-Si|-S|install)								shift;LSEARCHONLY=$false;LLIST=$true;sh_install "$@";return;;
 			-Sl|local)  									shift;sh_initinstallpkg "$@";exit;;
 			-Sa|alienpkg)	  		   					shift;fn_alienpkg_main "$@";return;;
-			-Sc|clean)  									shift;sh_clean "$@";exit;;
+#			-Sc|clean)  									shift;sh_clean "$@";exit;;
+			-Sc|clean)  									shift;fetchpack_init "$@";exit;;
 			-c|-C|create)					   			shift;fn_createpkg "$@";exit;;
 			-Sg|-g|generate)							   shift;fn_generatepkg "$@";exit;;
 			-Ss|search)	     								shift;sh_search "$@";exit;;
@@ -3375,3 +3612,4 @@ fi
 # CodeBlock?
 # Ponteiro=Var ; Var='Valor apontado'
 # echo ${!Ponteiro}
+
