sex 05 ago 2022 21:22:30 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/fetch b/fetch
--- a/fetch
+++ b/fetch
@@ -150,6 +150,7 @@ configure()
 		#SED_RE='^.+>(.+)-(([^-]+)-([0-9]+))-([^.]+)(.chi.zst)<.a>.*([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{2}-[A-z]{3}-[0-9]{4})[ ]([0-9]{2}:[0-9]{2}).*[ ]([0-9]+k?)(.*)'
 		#SED_RE='^.+="(.+)-(([^-]+)-([0-9]+))-([^.]+)(.chi.zst)".+<.a>.*([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{2}-[A-z]{3}-[0-9]{4})[ ]([0-9]{2}:[0-9]{2}).+[ ]([0-9]+k?)(.*)'
 		SED_RE='^.*["|\/](.+)-(([^-]+)-([0-9]+))-([^.]+)(.chi.zst)".+<.a>.*([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{2}-[A-z]{3}-[0-9]{4})[ ]([0-9]{2}:[0-9]{2}).+[ ]([0-9]+k?).*'
+		FETCH_RE='-[^-]+-[0-9]+-'
 	else
 		CHILI_OS=$false
 		#PKG_RE='(.+)-(([^-]+)-([0-9]+))\.mz' 						#SOEN
@@ -157,6 +158,7 @@ configure()
 #		PKG_RE_LYNX='(?!.*\/)(.+)-(([^-]+)-([0-9]))\.mz$'		#VC
 		GREP_RE='.mz\"'
 		SED_RE='^.+href="(.+)-(([^-]+)-([0-9]))()(\.mz\b)".+([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{2}-[A-z]{3}-[0-9]{4})[ ]([0-9]{2}:[0-9]{2})[ ]+([0-9]+[.]?[0-9]+.?).+'
+		FETCH_RE='-[^-]+-[0-9]+[.]'
 	fi
 }
 
@@ -3167,7 +3169,7 @@ fetchpack_configure()
 	declare -i delete=0 dryrun=0 move=0 totalsaved=0 pkgcount=0
 	declare -i verbose=0 ctime=0 QUIET=0
 	declare delim=$'\n'
-	declare keep=3
+	declare keep=1
 	declare movedir=
 	declare USE_COLOR='y'
 	# Expand to nothing if there are no matches
@@ -3194,17 +3196,7 @@ fetchpack_main()
 	local pkg_base=
 	local candidates=()
 	local cachedir
-	local re
-
-   #'[0-9]+([.][0-9]+)+'
-   #'-[0-9]+(.[0-9]+)+'
-   #'-[0-9]+([.][0-9]+)+'
-   #'[0-9]+([.][0-9]+)(.+)'
-   #'(([^-]+)-([0-9]+))-'
-   #'(.+)-(([^-]+)-([0-9]))-([^.]+)'
-   #'.*?(?=-[^-]+-[0-9]-.*)')
-   #'\-[^-]+-[0-9]-')
- 	re='-[^-]+-[0-9]+-'
+	local re=$FETCH_RE
 
 	if (( QUIET )); then
 		verbose=0
@@ -3222,7 +3214,7 @@ fetchpack_main()
 
 	for cachedir in "${cachedirs[@]}"
 	do
-		[[ -d $cachedir ]]            || die "Error: cachedir '$cachedir' does not exist or is not a directory"
+		[[ -d $cachedir ]]            || { log_failure_msg2 "${red}Error: cachedir '$cachedir' does not exist or is not a directory -- skipping"; continue; }
 		pushd "$cachedir" &>/dev/null || die "Error: failed to chdir to $cachedir"
 
 		if [ $# -lt 1 ]; then
@@ -3234,14 +3226,13 @@ fetchpack_main()
 		while read -r pkgInAll; do
 			pkg_base="$pkgInAll"
 			[[ -z "$pkg_base" ]] &&	continue
-			(( pkgNumber++ ))
+			((++pkgNumber))
 
 			if (( verbose >= 3 )); then
 				printf "  $(DOT)${white}candidate package ${purple}(%04d) ${green}%s\n" "$pkgNumber" "$pkg_base"
 			fi
-
-			candidates+=("$pkgInAll")
-			candesc+=("$pkgInAll.desc")
+			[[ -e "$pkgInAll"      ]] && candidates+=("$pkgInAll")
+			[[ -e "$pkgInAll.desc" ]] && candesc+=("$pkgInAll.desc")
 		done <<< "$AllOldPackages"  #done < <(printf '%s\n' "$AllOldPackages") #done <<< $(printf '%s\n' "$AllOldPackages")
 		popd >/dev/null 2>&1
 	done
@@ -3254,31 +3245,34 @@ fetchpack_main()
 	if (( verbose >= 2 )); then
 		pkgNumber=0
 		while read -r pkg; do
-			(( pkgNumber++ ))
+			((++pkgNumber))
 			printf "  $(DOT)${white}found package ${purple}(%04d) ${green}%42s\n" "$pkgNumber" "$pkg"
 		done <<< "$(printf '%s\n' "${candidates[@]}")"
 		#done < <(printf '%s\n' "${candidates[@]}") #done <<< "${candidates[@]}"
 	fi
 
-	pkgcount=$((${#candidates[*]} + ${#candesc[*]}))
-	totalsaved=$(printf '%s\0' "${candidates[@]}" | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
-	totalsaved+=$(printf '%s\0' "${candesc[@]}"   | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
+	ncandidates=${#candidates[*]}
+	ncandesc=${#candesc[*]}
+	pkgcount=$((ncandidates + ncandesc))
+
+	(( ncandidates )) && totalsaved=$(printf '%s\0' "${candidates[@]}" | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
+	(( ncandesc    )) && totalsaved+=$(printf '%s\0' "${candesc[@]}"   | xargs -0 stat -c %s | awk '{ sum += $1 } END { print sum }')
 	set -o errexit # Exit immediately if a pipeline returns non-zero.
 
 	if (( delete )); then
 		(( verbose )) && cmdopts+=(-v); cmdopts+=(-f)
-		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
-		printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 rm "${cmdopts[@]}"
+		(( ncandidates )) && printf '%s\0' "${candidates[@]}" | runcmd xargs -0 rm "${cmdopts[@]}"
+		(( ncandesc    )) && printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 rm "${cmdopts[@]}"
 	elif (( move )); then
 		(( verbose )) && cmdopts+=(-v); cmdopts+=(-f)
-		printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
-		printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
+		(( ncandidates )) && printf '%s\0' "${candidates[@]}" | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
+		(( ncandesc    )) && printf '%s\0' "${candesc[@]}"    | runcmd xargs -0 mv "${cmdopts[@]}" -t "$movedir"
 	elif (( verbose )); then
-		printf '%s\0' "${candidates[@]}" | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
-		printf '%s\0' "${candesc[@]}"    | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
+		(( ncandidates )) && printf '%s\0' "${candidates[@]}" | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
+		(( ncandesc    )) && printf '%s\0' "${candesc[@]}"    | xargs -0 printf "  $(DOT)%s\n" "${cmdopts[@]}"
 	fi
 
-	if (( !QUIET )); then
+	if (( ! QUIET )); then
 		if (( dryrun )); then
 			msg "${yellow}$output finish dry-run (packages found: $pkgcount with .desc) (disk space saved: %s)" "$(size_to_human "$totalsaved")"
 		else
@@ -3301,7 +3295,7 @@ ${red}     -r, --remove          ${reset}remove candidate packages.
   Options:
 ${red}     -c, --cachedir <dir>  ${reset}scan "dir" for packages. can be used more than once.
                            (default: read from /etc/fetch/fetch.conf).
-${red}     -k, --keep <num>      ${reset}keep "num" of each package in the cache (default: 3).
+${red}     -k, --keep <num>      ${reset}keep "num" of each package in the cache (default: 1).
 ${red}     -f, --force           ${reset}apply force to mv(1) and rm(1) operations.
 ${red}     -h, --help            ${reset}display this help message and exit.
 ${red}         --nocolor         ${reset}remove color from output.
@@ -3374,7 +3368,7 @@ fetchpack_init()
 
 	# setting default cachedirs
 	if [[ -z "${cachedirs[*]}" ]]; then
-		cachedirs=("${GITDIR:=/var/cache/fetch/archives}")
+		[[ -n "$GITDIR" ]] && cachedirs=("$GITDIR")
 		cachedirs+=("/var/cache/fetch/archives")
 	fi
 
