sáb 09 jul 2022 07:27:38 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/sena b/sena
--- a/sena
+++ b/sena
@@ -2,7 +2,7 @@
 #  sena - aplicativo para gerar numeros aleatorios da sena
 #
 #  Created: 2022/02/15
-#  Altered: 2022/07/08
+#  Altered: 2022/07/09
 #
 #  Copyright (c) 2022-2022, Benedito Ramos <diramos@uol.com.br>
 #  Copyright (c) 2022-2022, Vilmar Catafesta <vcatafesta@gmail.com>
@@ -34,12 +34,23 @@ fileresult="$CPATH/resultadosena.txt"
 fileUltSorteio='/tmp/UltSorteio.txt'
 fileUltSorteioAtualizado='/tmp/UltSorteioAtualizado.txt'
 SITE='https://servicebus2.caixa.gov.br/portaldeloterias/api/megasena/'
-_VERSION_='1.50.20220708'
-DEPENDENCIES=(curl wget grep printf mktemp sort sed awk tail cat tput)
+_VERSION_='1.79.20220709'
+DEPENDENCIES=(curl wget grep printf mktemp sort sed awk tail cat tput stat dialog)
 true=1
 false=0
 IFS=$' \t\n'
 SAVEIFS=$IFS
+sep='\xe2\x94\x82'
+
+# flag dialog exit status codes
+: ${D_OK=0}
+: ${D_CANCEL=1}
+: ${D_HELP=2}
+: ${D_EXTRA=3}
+: ${D_ITEM_HELP=4}
+: ${D_ESC=255}
+
+[ -e /chili/core.sh ] && source /chili/core.sh
 
 sh_playsena()
 {
@@ -54,7 +65,10 @@ sh_playsena()
 
   	LCONF=1
 	if [[ -e $filejogos ]]; then
-		conf "${red}:: ${reset}Existe um arquivo de jogos, deseja substitui-lo?"
+#		cfiledatahora=$(stat -c %w $filejogos)
+		cfiledatahora=$(date -r $filejogos +"%d/%m/%Y %T")
+		njogos=$(sh_linecount $filejogos)
+		conf "${red}:: ${reset}Existe arquivo de jogos gerado em: ${yellow}$cfiledatahora${reset} com ${red}$njogos${reset} palpites. Deseja substitui-lo?"
    	LCONF=$?
 	   if !(( $LCONF )); then
 			msg "Detalhes do arquivo de jogos feito"
@@ -72,12 +86,14 @@ sh_playsena()
 	declare -i outrametade=$metadeqtddezenas
 	declare -i n=0
 	declare -i njogosregistrados=0
+	local filelog=$(date +"%d%m%Y-%T" | sed 's/://g').log
 
    if (( $LCONF )); then
 		>| $filejogos
 	else
 		njogosregistrados=$(sh_linecount $filejogosformatado)
 	fi
+	>| $filelog
 
  	if [[ resto -gt 0 ]] ; then
 		((metadeqtddezenas++))
@@ -107,16 +123,16 @@ sh_playsena()
 		echo $line >> $filejogos
 		[[ $njogosregistrados -lt 10 ]] && var="Jogo "0"$njogosregistrados: " || var="Jogo $njogosregistrados: "
 		echo "$(date +"%d/%m/%Y %T") $var $line" >> $filejogosformatado
+		echo "$(date +"%d/%m/%Y %T") $var $line" >> $filelog
 	done
+	echo $(replicate '#' 80) >> $filejogosformatado
 	filetmp=$(mktemp)
 	sort $filejogos > $filetmp; cp $filetmp $filejogos; rm $filetmp 2> /dev/null
-	#chown www-data $filejogos
-	#chgrp www-data $filejogos
 }
 
 sh_linecount()
 {
-   awk 'END {print NR}' $1
+	awk 'END {print NR}' $1
 }
 
 die()
@@ -160,17 +176,17 @@ setvarcolors(){
       reset=$(tput sgr0);
       rst=$(tput sgr0);
       rs=$(tput sgr0);
-      blue=$(tput setaf 33);
-      cyan=$(tput setaf 37);
-      green=$(tput setaf 2);
-      orange=$(tput setaf 166);
-      purple=$(tput setaf 125);
-      red=$(tput setaf 124);
-      violet=$(tput setaf 61);
-      white=$(tput setaf 15);
-      yellow=$(tput setaf 136);
-      pink=$(tput setaf 129);
       black=$(tput setaf 0);
+      red=$(tput setaf 1);
+      green=$(tput setaf 2);
+      yellow=$(tput setaf 3);
+      blue=$(tput setaf 4);
+      pink=$(tput setaf 5);
+      cyan=$(tput setaf 6);
+      white=$(tput setaf 7);
+      orange=$(tput setaf 3);
+      purple=$(tput setaf 125);
+      violet=$(tput setaf 61);
    else
       bold='';
       reset="\e[0m";
@@ -241,9 +257,14 @@ comment
 
 	IFS=$'\n'
 	local re='[0-9]{2}[ ]?'
-	local aResult=($(awk -F'-' '{ print $3 }' $fileresult))
-	#local aJogos=($(awk -F "$re" 'lista[$1]++' $filejogos))
-	local aJogos=($(awk '{print " "$0}' $filejogos))
+	local reR='([0-9]{2}[ ])+((?1))+'
+	local reJ='([0-9]{2}[ ])?((?1))+'
+#	local aResult=($(awk -F'-' '{ print $3 }' $fileresult))
+#	local aJogos=($(awk '{print " "$0}' $filejogos))
+#	local aResult=($(awk -F "$reR" 'lista[$1]++' $fileresult))
+#	local aJogos=($(awk -F "$reJ" 'lista[$1]++' $filejogos))
+	local aResult=($(grep -Po "$reR" $fileresult))
+	local aJogos=($(grep -Po "$reJ" $filejogos))
 	local n=1
 	local value
 
@@ -265,6 +286,24 @@ comment
 	   ((n++))
 	done
 	IFS=$SAVEIFS
+}
+
+sh_compareGREP()
+{
+	local re='[0-9]{2}[ ]?'
+	local reR='([0-9]{2}[ ])+((?1))+'
+	local reJ='([0-9]{2}[ ])?((?1))+'
+
+	[[ ! -e $filejogos ]] && { erro "erro: nenhum jogo realizado ainda para comparação. (use -h for help)"; exit 1;}
+	nsize=$(filesize $filejogos)
+	[[ $nsize -eq 0    ]] && { erro "erro: nenhum jogo realizado ainda para comparação. (use -h for help)"; exit 1;}
+
+	msg "Fazendo chegagem das jogadas. Aguarde..."
+	if ! value=$(grep -s -o -f $filejogos $fileresult); then
+		printf "${green}OK ↑ nenhuma jogada armazenada foi encontrada no BD${reset}\n"
+	else
+		printf "Jogos ${cyan}\n$value\n${red}FALHA ↓ Já existe(m) no BD${reset}\n"
+	fi
 }
 
 sh_atualizaBD()
@@ -373,6 +412,66 @@ sh_listarjogos()
 	more $filejogosformatado
 }
 
+replicate()
+{
+   local Var
+   printf -v Var %$2s " "  #  Coloca em $Var $1 espaços
+   echo ${Var// /$1}       #  Troca os espaços pelo caractere escolhido
+}
+
+choosefile()
+{
+   while true
+   do
+   	pushd $CPATH &>/dev/null
+      ARRAY_FILE_LOG=($(find *.log -type f 2>/dev/null))
+      popd &>/dev/null
+     	[[ "${#ARRAY_FILE_LOG[@]}" -eq 0 ]] && die "erro: arquivo log de jogos ainda não existe. Faça alguns jogos primeiro. (use -h for help)"
+      local array=()
+      local i
+      local n=0
+      local nc=0
+
+      for i in "${ARRAY_FILE_LOG[@]}"
+      do
+      	array[((n++))]="$i"
+         array[((n++))]=$(printf "%-6s$sep%5s PALPITES" "$(date -r $i +"%d/%m/%Y %T")" "$(sh_linecount $i)")
+         ((nc++))
+      done
+
+      sd=$(dialog                                                                \
+               --title        "${cmsg_disco_origem[$LC_DEFAULT]}"                \
+               --backtitle 	"${0##*/} v${_VERSION_}"									\
+               --ok-label     "Visualizar"						                     \
+               --cancel-label "Sair"   									               \
+               --colors                                                          \
+               --extra-button                                                    \
+               --extra-label  "Excluir"								                  \
+               --menu         "\nArquivos Log de jogos"  			               \
+               0 0 0 "${array[@]}" 2>&1 >/dev/tty  )
+
+      exit_status=$?
+      case $exit_status in
+			$D_OK)
+		      if test ! -z "$sd"; then
+      		   display_result $sd
+      		fi
+      		;;
+         $D_ESC|$D_CANCEL)
+            exit
+            ;;
+         3)
+				conf "${red}:: ${reset}Deseja excluir o arquivo $sd ?"
+   			LCONF=$?
+	   		if (( $LCONF )); then
+            	rm -f $CPATH/$sd
+            	continue
+            fi
+            ;;
+      esac
+	done
+}
+
 sh_usage()
 {
 	cat <<EOF
@@ -390,6 +489,17 @@ ${orange}uso:${reset}
 EOF
 }
 
+display_result()
+{
+	dialog      --title  "$1" 									\
+               --no-collapse              				\
+               --no-cr-wrap               				\
+               --beep                     				\
+               --backtitle "${0##*/} v${_VERSION_}"	\
+               --textbox   "$1"           				\
+               0 0
+}
+
 init()
 {
    while test $# -gt 0
@@ -397,7 +507,8 @@ init()
       case "${1}" in
 		   -h|--help) sh_usage; exit $(( $# ? 0 : 1 ));;
    		-c|--compare) sh_compare; exit $(( $# ? 0 : 1 ));;
-   		-l|--log) sh_listarjogos; exit $(( $# ? 0 : 1 ));;
+#   		-l|--log) sh_listarjogos; exit $(( $# ? 0 : 1 ));;
+   		-l|--log) choosefile; exit $(( $# ? 0 : 1 ));;
    		-U|--update) sh_resultadosena; exit $(( $# ? 0 : 1 ));;
    		-V|--version) sh_logo; exit $(( $# ? 0 : 1 ));;
    		-j|--jogo)
