seg 11 jul 2022 01:25:02 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/sena b/sena
--- a/sena
+++ b/sena
@@ -2,7 +2,7 @@
 #  sena - aplicativo para gerar numeros aleatorios da sena
 #
 #  Created: 2022/02/15
-#  Altered: 2022/07/10
+#  Altered: 2022/07/11
 #
 #  Copyright (c) 2022-2022, Benedito Ramos <diramos@uol.com.br>
 #  Copyright (c) 2022-2022, Vilmar Catafesta <vcatafesta@gmail.com>
@@ -29,7 +29,7 @@
 #global
 
 #system
-_VERSION_='2.26.20220710'
+_VERSION_='2.28.20220711'
 DEPENDENCIES=(curl wget grep printf mktemp sort sed awk tail cat tput stat dialog find jq)
 
 #paths/files/urls
@@ -265,6 +265,23 @@ setvarcolors(){
    fi
 }
 
+unsetvarcolors()
+{
+   bold=
+   reset=
+   black=
+   blue=
+   cyan=
+   green=
+   orange=
+   purple=
+   red=
+   violet=
+   white=
+   yellow=
+   pink=
+}
+
 log_prefix()
 {
    NORMAL="${reset}"            # Standard console grey
@@ -304,6 +321,21 @@ evaluate_retval()
    return ${error_value}
 }
 
+log_info_msg2()
+{
+    echo -n -e "${@}"
+    logmessage=`echo "${@}" | sed 's/\\\033[^a-zA-Z]*.//g'`
+    echo -n -e "${logmessage}" >> ${BOOTLOG}
+    return 0
+}
+
+log_failure_msg2()
+{
+   printf "${BMPREFIX}${@}"
+   printf "${CURS_ZERO}${FAILURE_PREFIX}${SET_COL}${FAILURE_SUFFIX}\n"
+   return 0
+}
+
 log_wait_msg()
 {
    printf "${BMPREFIX}${@}"
@@ -324,6 +356,17 @@ log_msg()
    return 0
 }
 
+toupper()
+{
+	declare -u TOUPPER=${@}
+	echo -e "${TOUPPER}"
+}
+
+tolower()
+{
+	declare -l TOLOWER=${@}
+	echo -e "${TOLOWER}"
+}
 
 check_deps()
 {
@@ -469,18 +512,22 @@ sh_checkresultadosfaltantes()
 
 
 	log_info_msg "Checando a integridade do BD. Aguarde..."; evaluate_retval
-	if [[ $numUltSorteioGravado -eq 0 ]]; then
-		if sh_checknet "${URL_GITHUB_RESULTADOSENA}"; then
-			#curl --compressed --insecure -s --url "${URL_GITHUB_RESULTADOSENA}" --output $fileresult
-			log_info_msg "Baixando arquivo ${URL_GITHUB_RESULTADOSENA}"
-			if ! wget -c --no-check-certificate "${URL_GITHUB_RESULTADOSENA}" -qO - > $fileresult; then
+	if !(( force )); then
+		if [[ $numUltSorteioGravado -eq 0 ]]; then
+			if sh_checknet "${URL_GITHUB_RESULTADOSENA}"; then
+				#curl --compressed --insecure -s --url "${URL_GITHUB_RESULTADOSENA}" --output $fileresult
+				log_info_msg "Baixando arquivo ${URL_GITHUB_RESULTADOSENA}"
+				if ! wget -c --no-check-certificate "${URL_GITHUB_RESULTADOSENA}" -qO - > $fileresult; then
+					echo "#" >> $fileresult
+				fi
+				evaluate_retval
+			else
+				evaluate_retval
 				echo "#" >> $fileresult
 			fi
-			evaluate_retval
-		else
-			evaluate_retval
-			echo "#" >> $fileresult
 		fi
+	else
+		echo "#" > $fileresult
 	fi
 
 	seq "$numUltSorteio" > $filetmp
@@ -523,6 +570,10 @@ sh_update()
 	else
 		numUltSorteio=$(jq -r '.numero' $fileUltSorteio)
 		numUltSorteioGravado=$(awk 'END {print NR}' "$fileresult")
+	fi
+
+	if (( force )); then
+		numUltSorteioGravado=0
 	fi
 
 	#### COLETANDO DADOS DOS DOS RESULTADOS NAO INCLUÍDOS NO BD
@@ -641,6 +692,7 @@ ${orange}uso:${reset}
    sena ${pink}-c|--compare${cyan}        # comparar palpites com o BD${reset}
    sena ${pink}-l|--log${cyan}            # exibir log de palpites efetuados${reset}
    sena ${pink}-U|--update${cyan}         # atualizar BD com a CAIXA${reset}
+   sena ${pink}-F|--force${cyan}          # força a atualização do zero do BD com a CAIXA${reset}
    sena ${pink}-V|--version${cyan}        # exibe versão do aplicativo${reset}
 EOF
 }
@@ -666,6 +718,7 @@ init()
    		-c|-C|--compare) sh_compare; exit $(( $# ? 0 : 1 ));;
    		-l|-L|--log) choosefile; exit $(( $# ? 0 : 1 ));;
    		-U|--update) sh_update; exit $(( $# ? 0 : 1 ));;
+   		-F|--force) force=$true; sh_update; exit $(( $# ? 0 : 1 ));;
    		-V|--version) sh_logo; exit $(( $# ? 0 : 1 ));;
    		-j|-J|--jogo)
 				shift;
@@ -687,6 +740,7 @@ setvarcolors
 log_prefix
 check_deps
 sh_ascii-lines
+param="$@"
 
 [[ -z $1 ]] && { sh_usage; exit $(( $# ? 0 : 1 ));}
 init "$@"
